# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'app-divine-lake-858'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  JVM_OPTS = '-Xmx384m -Xms256m'
  HALO_WORK_DIR = '/data/halo2'
  SPRING_CONFIG_LOCATION = 'optional:classpath:/;optional:file:/data/halo2/'
  TZ = 'UTC'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 80

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = 'halo_data'
  destination = '/data/halo2'
