[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/actuator/health/readiness"
healthcheckTimeout = 120
startCommand = ""
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
