apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: additional-webfilter
spec:
  className: run.halo.app.security.AdditionalWebFilter
  displayName: "Additional Web Filter"
  type: MULTI_INSTANCE
  description: "Chain processing for web requests, used to implement cross-cutting, application-independent concerns such as security, timeouts, etc."

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: reactive-post-content-handler
spec:
  className: run.halo.app.theme.ReactivePostContentHandler
  displayName: "Post Content Handler"
  type: MULTI_INSTANCE
  description: "Extends the post content displayed on the theme side"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: reactive-singlepage-content-handler
spec:
  className: run.halo.app.theme.ReactiveSinglePageContentHandler
  displayName: "Page Content Handler"
  type: MULTI_INSTANCE
  description: "Extends the page content displayed on the theme side"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: comment-widget
spec:
  className: run.halo.app.theme.dialect.CommentWidget
  displayName: "Comment Widget"
  type: SINGLETON
  description: "Extends the comment widget displayed on post pages"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: username-password-authentication-manager
spec:
  className: run.halo.app.security.authentication.login.UsernamePasswordAuthenticationManager
  displayName: "Username Password Authentication Manager"
  type: SINGLETON
  description: "Extends username and password authentication"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: reactive-notifier
spec:
  className: run.halo.app.notification.ReactiveNotifier
  displayName: "Notification Sender"
  type: MULTI_INSTANCE
  description: "Extends the notification sender to deliver notifications to users"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: search-engine
spec:
  className: run.halo.app.search.SearchEngine
  displayName: "Search Engine"
  type: SINGLETON
  description: "Extends the content search engine"

---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: template-footer-processor
spec:
  className: run.halo.app.theme.dialect.TemplateFooterProcessor
  displayName: Footer Tag Content Processor
  type: MULTI_INSTANCE
  description: "Provides an extension mechanism for the <halo:footer/> tag content."
---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: excerpt-generator
spec:
  className: run.halo.app.content.ExcerptGenerator
  displayName: Excerpt Generator
  type: SINGLETON
  description: "Provides an extension for auto-generating excerpts, such as using algorithmic extraction or AI generation."
---
apiVersion: plugin.halo.run/v1alpha1
kind: ExtensionPointDefinition
metadata:
  name: thumbnail-provider
spec:
  className: run.halo.app.core.attachment.ThumbnailProvider
  displayName: Image Thumbnail Generator
  type: MULTI_INSTANCE
  description: "Provides an extension for generating image thumbnails"
